name: Greetings

on: push

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - run: "echo Step 1"
    - run: "echo ::debug::Step 2"
