name: Print Inputs

on:
  workflow_dispatch:
    inputs: 
      log_levels:
        description: 'Log Level'
        required: true
        default: 'info'
        type: choice
        options: 
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Tags'
        required: true
        type: string
      environment:
        description: 'Environment'
        type: environment
        required: true
        
jobs:
  print-inputs:
    runs-on: ubuntu-latest
    if: ${{ inputs.print_tags }}
    steps:
      - name: Print the input tag to STDOUT
        run: |
          echo \
            Log level: ${{ inputs.log_levels }}, \
            PrintTags: ${{ inputs.print_tags }} \
            Tags: ${{ inputs.tags }} \
            Env: ${{ inputs.environment }}, Vars ${{ vars.ENV_NAME }}
            
