# .github/workflows/build.yml
name: Node Build.

on: [push, workflow_dispatch]

jobs:
    prebuild:
        runs-on: [ubuntu-latest]
        steps:
        - name: echoing prebuild
          run: echo "prebuild"
          
    mainbuild:
        runs-on: ${{ matrix.os }}    
        strategy:
            matrix:
                node-version: [12.x, 13.x, 14.x, 15.x]
                os: [windows-latest, ubuntu-latest, macos-latest]
        steps:
        - uses: actions/checkout@v1
        - name: Run node.js on latest Windows.
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install NPM and build.
          run: |
            npm ci
            npm npm init --yes
