# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build continuous integration (CI) workflows by using GitHub Actions

on: [push, workflow_dispatch]

jobs:
  prod-check:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      
  dev-check:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - run: echo "Deploying to dev server on branch $GITHUB_REF"
