# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build continuous integration (CI) workflows by using GitHub Actions

on: [push, workflow_dispatch]

jobs:
  upload:
    name: Upload File
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:

      - name: Print text to file
        run: echo "Deploying to production server on branch $GITHUB_REF, changed by $AUTHOR_NAME" > $FILE_NAME
        env:
          FILE_NAME: info.txt
          AUTHOR_NAME: Bartek

      - name: Upload $FILE_NAME artifact
      - uses: actions/upload-artifact@v2
        with: 
          name: info
          path: info.txt
          
  download:
    name: Download File
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Download $FILE_NAME
        uses: actions/download-artifact@v2
        with:
          name: info
      - name: Print artifact content
        run: cat info.txt
