# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Download Upload file

on: [workflow_dispatch, push]

env:
  FILE_NAME: info.txt
  FILE_PATH: info
  
jobs:
  upload:
    name: Upload File
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    
    steps:
      - name: Print text to $FILE_NAME, run by ${{ github.actor }}
        run: echo "Deploying artifact on branch ${{ github.ref }}, changed by ${{ github.actor }}" > ${{ env.FILE_NAME }}
      - name: Upload ${{ env.FILE_NAME }} artifact
        uses: actions/upload-artifact@v2
        with: 
          name: ${{ env.FILE_PATH }}
          path: ${{ env.FILE_NAME }}
          
  download:
    name: Download File
    runs-on: ubuntu-latest
    needs: upload
    if: ${{ success() }}
    steps:
      - name: Download ${FILE_NAME}
        uses: actions/download-artifact@v2
        with:
          name: ${FILE_PATH}
      - name: Print artifact content
        run: cat info.txt
