name: Workflow commands

on: 
  workflow_dispatch:
    inputs: 
      debug: 
        required: false
        description: Turn on debug ?
        options: 
          - 'yes'
          - 'no'

jobs:
  commands:
    environment: ${{ input.debug == 'yes' && 'dev' || '' }}
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Print debug message
      run: |
        echo "::debug::Debug message"
    - name: Step 2 - Create notice
      run: |
        echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
