name: Workflow commands

on: 
  workflow_dispatch:
    inputs: 
      log_levels:
        description: 'Log Level'
        required: true
        default: 'info'
        type: choice
        options: 
          - info
          - warning
          - debug
      print_debug: 
        description: 'Turn on debug ?'
        type: choice
        required: true
        default: 'yes'
        options: 
          - yes
          - no

jobs:
  commands:
    environment: ${{ inputs.print_debug == 'yes' && 'dev' || '' }}
    runs-on: ubuntu-latest
    steps:
    - name: Step 0 - Print env
      run: |
        echo ${{ inputs.debug == 'yes' && 'dev' || '' }}
        
    - name: Step 1 - Print debug message
      run: |
        echo "::debug::Debug message"
        
    - name: Step 2 - Create notice
      run: |
        echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
        
    - name: Step 3 - Create warning
      run: |
        echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"

    - name: Step 4 - Create error
      run: |
        echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"

