${{ inputs.print_debug == 'turn on' && 'dev' || '' }}name: Workflow commands

on: 
  workflow_dispatch:
    inputs:
      print_debug: 
        description: 'Turn on debug ?'
        type: choice
        required: true
        default: 'turn on'
        options: 
          - 'turn on'
          - 'turn off'

jobs:
  commands:
    environment: ${{ inputs.print_debug == 'turn on' && 'dev' || '' }}
    runs-on: ubuntu-latest
    steps:
    - name: Step 0 - Print env
      env:
        PRINT_DEBUG: ${{ inputs.print_debug == 'turn on' && 'dev' || '' }}
      run: |
        echo Env $PRINT_DEBUG
     
        
    - name: Step 1 - Print debug message
      run: |
        echo "::debug::Debug message"
        
    - name: Step 2 - Create notice
      run: |
        echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
        
    - name: Step 3 - Create warning
      run: |
        echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"

    - name: Step 4 - Create error
      run: |
        echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"

